### ISSUE TITLE
api timeout

### ISSUE THREAD

**Issue by x-shadow-x** [talentappstore/gauge#3]
Hi abraae! I encountered a problem recently.The scene is like this:
In order to facilitate users to get the latest assets in time, I will consume ` /assessmentTypes/forApp/deltaPings/1` when responding to `/appStatus`. When the notification is complete, return the response of the `/appStatus` request.However, the button status on the storefront has not changed. I did an experiment and used `async/await` to simulate `/assessmentTypes/forApp/deltaPings/1`. If the resolve time is increased, the store button status will not be set correctly. It seems that the `/appStatus` request timed out. Is there any method can set the timeout of `Produced APIs`? Looking forward to your reply!

**Comment by abraae** [comment]
This is really a general question about building assessment apps, so I think your question should be directed to here: https://devdiscourse.talentappstore.com/

However here are some thoughts:

/assessmentTypes/forApp/deltaPings/1
------
/assessmentTypes/forApp/deltaPings/1 is what you consume to tell TAS (the assessment hub more precisely) that your list of assessments has **changed**.

So if you always have one and only one assessment type, then you would never need to call this.

There is one common exception though - when setup has been completed on your app. At that time your list of working assessments typically goes from zero to one, so that would be a good time to call this API - immediately after setup has been completed.

Summary: only call /assessmentTypes/forApp/deltaPings/1 when your list of assessment types has changed.

/appStatus
----
You produce this API in order to signal to TAS (more precisely the storefront app) whether your app needs setup or not.

So I don't see any reason to consume /assessmentTypes/forApp/deltaPings/1 while you are responding to /appStatus - it doesn't really make sense.

However - when setup is complete (e.g. the user has done whatever you need them to do from the setup button - like connected their account in your own platform for example) then you might call /assessmentTypes/forApp/deltaPings/1.

That would signal the assessment hub "Aha! Something's changed - this app has new assessment types!". Next thing, the assessment hub will start calling other APIs on you to get the precise list of assessment types that you now offer.

I hope that makes sense, but as I say, these are really general question about building assessment apps and you should ask them at https://devdiscourse.talentappstore.com/.

**Comment by x-shadow-x** [comment]
Thank you so much for your reply!&nbsp;And I will make some logical adjustments~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年3月12日(星期四) 中午11:10
收件人: "talentappstore/gauge"<gauge@noreply.github.com&gt;; 
抄送: "影子"<2509344578@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [talentappstore/gauge] api timeout (#3)





 
This is really a general question about building assessment apps, so I think your question should be directed to here: https://devdiscourse.talentappstore.com/
 
However here are some thoughts:
 
/assessmentTypes/forApp/deltaPings/1
 
/assessmentTypes/forApp/deltaPings/1 is what you consume to tell TAS (the assessment hub more precisely) that your list of assessments has changed.
 
So if you always have one and only one assessment type, then you would never need to call this.
 
There is one common exception though - when setup has been completed on your app. At that time your list of working assessments typically goes from zero to one, so that would be a good time to call this API - immediately after setup has been completed.
 
Summary: only call /assessmentTypes/forApp/deltaPings/1 when your list of assessment types has changed.
 
/appStatus
 
You produce this API in order to signal to TAS (more precisely the storefront app) whether your app needs setup or not.
 
So I don't see any reason to consume /assessmentTypes/forApp/deltaPings/1 while you are responding to /appStatus - it doesn't really make sense.
 
However - when setup is complete (e.g. the user has done whatever you need them to do from the setup button - like connected their account in your own platform for example) then you might call /assessmentTypes/forApp/deltaPings/1.
 
That would signal the assessment hub "Aha! Something's changed - this app has new assessment types!". Next thing, the assessment hub will start calling other APIs on you to get the precise list of assessment types that you now offer.
 
I hope that makes sense, but as I say, these are really general question about building assessment apps and you should ask them at https://devdiscourse.talentappstore.com/.
